version: '3'

services:
  app:
    image: blog_back_app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - '9002:9001'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blog
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
    - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog