server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect

  liquibase:
    change-log: classpath:/data/changelog/db.changelog.master.xml

jwt:
  secret: jwtsecret